### ISSUE TITLE
Контрольная №2. Вопрос №3. Результат

### ISSUE THREAD

**Issue by Citronnn** [OSLL/moodle_sql_task_generator#11]
Ожидаемый результат не удовлетворяет условию задачи.

![image](https://user-images.githubusercontent.com/21692744/128635111-d17d976b-89aa-45da-85ad-8b6f28781e08.png)

![image](https://user-images.githubusercontent.com/21692744/128635148-6ff1e566-2b78-4fd3-b517-8fcb8c071c22.png)

**Comment by kovinevmv** [comment]
Подразумевалось изменение поле цена. Отформатировал для более явного вида

![Screenshot from 2021-08-17 23-26-15](https://user-images.githubusercontent.com/21666349/129795672-7585dc7d-ff70-4835-a7b5-60e9a8969501.png)
