### ISSUE TITLE
Контрольная №2. Вопрос №10. Синтаксис

### ISSUE THREAD

**Issue by Citronnn** [OSLL/moodle_sql_task_generator#12]
column обязательное? (https://www.w3schools.com/sql/trysql.asp?filename=trysql_alter_table)

![image](https://user-images.githubusercontent.com/21692744/128635278-2838754e-67a3-4223-9093-aa9ba6ae31ec.png)

**Comment by kovinevmv** [comment]
Убрал обязательность column
