### ISSUE TITLE
Доп. контрольная №2. Вопрос №7. Формулировка

### ISSUE THREAD

**Issue by Citronnn** [OSLL/moodle_sql_task_generator#13]
Формулировка подразумевает, что требуется найти количество книг в наличии, т.е. если у автора 2 книги (первой - 5 шт, второй - 3), то ответ для автора 8, а программа подсчитывает просто кол-во книг (кол-во записей по сути), и даст ответ 2 вместо 8. 

![image](https://user-images.githubusercontent.com/21692744/128636045-ed77e28c-bbd9-4468-b55c-b50eb28858b6.png)

**Comment by kovinevmv** [comment]
Исправил на:
```
Вывести информацию об авторе (author) и суммарное количество его книг в наличии (amount) из таблицы книги
```
Теперь требует sum вместо count
