### ISSUE TITLE
Доп. контрольная №1. Задание №5. Требуется написать неверный SQL

### ISSUE THREAD

**Issue by SqrtMinusOne** [OSLL/moodle_sql_task_generator#20]
Видимо, требуется ответ:
```sql
SELECT sum(column_1), count("COLUMN_2"), round(column_3) FROM cats
```

Но он не может работать: https://www.db-fiddle.com/f/rbkqtgsZzeyDXTHf1TK4Tm/0

**Comment by kovinevmv** [comment]
Согласен, что-то об этом не подумал, вынесу в написание трех отдельных запросов

**Comment by kovinevmv** [comment]
Исправил на 3 запроса, нужно проверить еще раз. И уточнить бы формулировку
