### ISSUE TITLE
Контрольная №2. Вопрос №4. Сортировка

### ISSUE THREAD

**Issue by Citronnn** [OSLL/moodle_sql_task_generator#3]
![image](https://user-images.githubusercontent.com/21692744/125481219-b4e0fc5e-3a86-4b7d-8a27-e3d5839718ff.png)

В задании сказано "первых" 13, но не указано первых по какому критерию

**Comment by kovinevmv** [comment]
Исправлено. Теперь текст звучит так:
> Средствами SQL запросов, выведите название товара (ProductName), размеры (Unit), цену (Price), количество (Quantity) первых 12 самых больших заказов относительно количества товаров (Quantity)
