### ISSUE TITLE
Контрольная №2. Вопрос №9. Вывод

### ISSUE THREAD

**Issue by Citronnn** [OSLL/moodle_sql_task_generator#5]
![image](https://user-images.githubusercontent.com/21692744/125481725-8470ea2b-6540-47c7-953c-edd241262a9d.png)

Формулировка подразумевает только обновление
Однако, ответ требует ещё и выборку

![image](https://user-images.githubusercontent.com/21692744/125481836-09f256cd-5b64-4d8c-be57-604b62792587.png)

**Comment by kovinevmv** [comment]
Нет, выборка потом склеивается после ответа студента для того, чтобы понять, что обновил студент

**Comment by kovinevmv** [comment]
@Citronnn 
![image](https://user-images.githubusercontent.com/21666349/125503839-2e3b78fc-de2c-4f56-bfb1-24a363af1917.png)
