### ISSUE TITLE
Контрольная №1. Вопрос №1. Регистр

### ISSUE THREAD

**Issue by Citronnn** [OSLL/moodle_sql_task_generator#7]
В данном диалекте регистр влияет на тип данных?

![image](https://user-images.githubusercontent.com/21692744/128633929-1bc147a0-3d17-4db0-a70c-5f876995319f.png)

**Comment by kovinevmv** [comment]
Прикрепил сообщение, что типы чувствительны к регистру

![Screenshot from 2021-08-17 21-58-28](https://user-images.githubusercontent.com/21666349/129784801-7e49cd30-1d45-41e0-8456-766d291ab685.png)
