### ISSUE TITLE
Доп. контрольная №1. Вопрос №7. Формулировка

### ISSUE THREAD

**Issue by Citronnn** [OSLL/moodle_sql_task_generator#8]
Неочевидно, что требуется использовать like (другие варианты приняты не будут). Лучше что-то из разряда "у которых имя автора содержит Durrell" (что-то такое).

![image](https://user-images.githubusercontent.com/21692744/128634015-17289af1-6605-4c44-98ca-f31fe15329ff.png)

**Comment by kovinevmv** [comment]
Добавил текст: 
```
Примечание: стоит учесть, что в столбце автор может содержаться не один автор, а несколько через запятую
```
