### ISSUE TITLE
Контрольная №2. Вопрос №2. Cast

### ISSUE THREAD

**Issue by Citronnn** [OSLL/moodle_sql_task_generator#9]
Обязательное использование CAST неочевидно

![image](https://user-images.githubusercontent.com/21692744/128635013-dd88692f-3b7c-4317-9026-4fd3b611de64.png)

**Comment by SqrtMinusOne** [comment]
Ага, я пытался FLOOR сначала

**Comment by kovinevmv** [comment]
Добавил примечание:
```
SQLite не содержит функции округления, однако можно привести дробный тип к целому через CAST или воспользоваться формулой ROUND(x - 0.5) = FLOOR
```

Обязтальность CAST убрал

**Comment by Citronnn** [comment]
Floor также недоступно и его упоминание может запутать. Теперь задание не соответствует решению (просят "целая часть - чётное", а в ответе "7.9, 7.3, 5.3 и т.д."

**Comment by SqrtMinusOne** [comment]
Я бы написал просто `функция FLOOR недоступна, можно воспользоваться "CAST" или "ROUND"`

**Comment by kovinevmv** [comment]
> Floor также недоступно и его упоминание может запутать. Теперь задание не соответствует решению (просят "целая часть - чётное", а в ответе "7.9, 7.3, 5.3 и т.д."

Исправлено описание, ожидается нечетное

**Comment by kovinevmv** [comment]
> Я бы написал просто `функция FLOOR недоступна, можно воспользоваться "CAST" или "ROUND"`

Исправил описание
